name: Deploy to Heroku

on:
  push:
    branches:
      - main  # Trigger deployment on push to the 'main' branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'  # Specify the Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r backend/requirements.txt  # Install dependencies

    - name: Install Heroku CLI
      run: |
        curl https://cli-assets.heroku.com/install.sh | sh  # Install Heroku CLI

    - name: Log in to Heroku
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      run: |
        echo "$HEROKU_API_KEY" | heroku auth:token

    - name: Deploy to Heroku
      run: |
        heroku git:remote -a your-heroku-app-name
        git push heroku main

